os: linux
dist: xenial
services:
  - docker

# https://www.digitalrooster.dev/news/travis-updated-docker/
script:
  - P=ubuntu1604 && docker build . -t $P -f .travis/Dockerfile.$P && docker run $P
  - P=ubuntu1804 && docker build . -t $P -f .travis/Dockerfile.$P && docker run $P
  - P=ubuntu2004 && docker build . -t $P -f .travis/Dockerfile.$P && docker run --privileged $P
  - P=ubuntu2010 && docker build . -t $P -f .travis/Dockerfile.$P && docker run --privileged $P

notifications:
  irc:
    channels:
      - "chat.freenode.net#albertlauncher"
    on_success: change
    on_failure: always
